export CLICOLORS=true
export DIRCOLORS=yes

# Interface
alias ls='ls -G'
alias flush='dscacheutil -flushcache'
alias lookup='ssh -t kt2384@cunix.columbia.edu lookup'

# Now, the cool stuff.
alias vi='/usr/bin/vim'
alias vim='/Applications/MacVim.app/Contents/MacOS/Vim'
alias vimdiff='/Applications/MacVim.app/Contents/MacOS/Vim -d'
alias ttop='/usr/bin/top -ocpu -R -F -s 2 -n30'
alias clj='rlwrap clj'
alias klast='jobs -p | tail -n 1 | xargs kill && fg'
alias to_txt='textutil -stdout -convert txt '

function mcd() {
  mkdir -p "$1"
  cd "$1"
}
alias pkill=killall
alias ll='ls -lah'

export EDITOR=vim
# Personal stuff

case $TERM in
  xterm*|rxvt*)
    TITLEBAR='\[\033]0;\u@\h:\w\007\]'
    ;;
  *)
    TITLEBAR=""
    ;;
esac;
#  Prompt generated by Giles's Prompt-o-matic, 20110111
#  http://www.gilesorr.com/bashprompt/jsb/prompt.html
tty=$(tty)
PS1="${TITLEBAR}\[\033[0m\]\[\033[0;32m\]\h:\W \j ${tty:9}/\!\[\033[0;32m\]\[\033[47m\]\[\033[0;30m\]\[\033[42m\]\$\[\033[0;0m\] "

if [ -f `brew --prefix`/etc/bash_completion ]; then
. `brew --prefix`/etc/bash_completion
fi
export GEM_HOME="$(brew --prefix)/Cellar/gems/1.8"

PATH="/Applications/MATLAB_R2011b.app/bin:/usr/local/texlive/2010/bin/x86_64-darwin:/usr/local/bin:/usr/local/sbin:$PATH"

# Setting PATH for EPD-7.2-1
# The orginal version is saved in .bash_profile.pysave
PATH="/Library/Frameworks/EPD64.framework/Versions/Current/bin:${PATH}"
export PATH

# We have Python modules (namely, mpi.so) in /usr/local/lib
export PYTHONPATH="/usr/local/lib:$PYTHONPATH"

#MKL_NUM_THREADS=2
#export MKL_NUM_THREADS

