export CLICOLORS=true
export DIRCOLORS=yes

# Interface
alias ls='ls -G'
alias vim='/Applications/MacVim.app/Contents/MacOS/Vim'
alias vi='/usr/bin/vim'

# Now, the cool stuff.
alias ttop='/usr/bin/top -ocpu -R -F -s 2 -n30'
alias clj='rlwrap clj'
alias t='~/Dropbox/dotfiles/todo.sh'
alias klast='jobs -p | tail -n 1 | xargs kill && fg'
alias to-txt='textutil -stdout -convert txt '

function cd() {
  pushd "$1" >/dev/null
}
function mcd() {
  mkdir -p "$1"
  cd "$1"
}
alias b=popd
alias pkill=killall
alias ll='ls -lah'
# Personal stuff
function blog() {
  pushd ~/Dropbox/kui-tang.com
  ./write.sh $1 $2
  popd
}

# Git
alias push='git push origin master'
alias pull='git pull origin master'

case $TERM in
  xterm*|rxvt*)
    TITLEBAR='\[\033]0;\u@\h:\w\007\]'
    ;;
  *)
    TITLEBAR=""
    ;;
esac;
#  Prompt generated by Giles's Prompt-o-matic, 20110111
#  http://www.gilesorr.com/bashprompt/jsb/prompt.html
tty=$(tty)
PS1="${TITLEBAR}\[\033[0m\]\[\033[0;32m\]\h:\W \j ${tty:9}/\!\[\033[0;32m\]\[\033[47m\]\[\033[0;30m\]\[\033[42m\]\$\[\033[0;0m\] "

if [ -f `brew --prefix`/etc/bash_completion ]; then
. `brew --prefix`/etc/bash_completion
fi
export GEM_HOME="$(brew --prefix)/Cellar/gems/1.8"

PATH="/usr/local/bin:/usr/local/sbin:$PATH"
